// <auto-generated />
using System;
using BibliothèqueUniversitaire.ApplicationWpfCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BibliothèqueUniversitaire.WpfCore.Migrations
{
    [DbContext(typeof(ModelContext))]
    partial class ModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AuteurEntityLivreEntity", b =>
                {
                    b.Property<long>("AuteursId")
                        .HasColumnType("bigint");

                    b.Property<long>("LivresNuméro")
                        .HasColumnType("bigint");

                    b.HasKey("AuteursId", "LivresNuméro");

                    b.HasIndex("LivresNuméro");

                    b.ToTable("AuteurEntityLivreEntity");
                });

            modelBuilder.Entity("BibliothèqueUniversitaire.ApplicationWpfCore.Models.EmpruntEntity", b =>
                {
                    b.Property<long>("NumEmrunt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("num_emprunt")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AdherentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateEmprunt")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_emprunt");

                    b.Property<DateTime>("DateRetourEmprunt")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_retour_emprunt");

                    b.Property<long?>("LivreEmpruntéNuméro")
                        .HasColumnType("bigint");

                    b.HasKey("NumEmrunt");

                    b.HasIndex("AdherentId");

                    b.HasIndex("LivreEmpruntéNuméro");

                    b.ToTable("emprunt", "dbo");
                });

            modelBuilder.Entity("BibliothèqueUniversitaire.ApplicationWpfCore.Models.LivreEntity", b =>
                {
                    b.Property<long>("Numéro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("numéro")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("NbrPages")
                        .HasColumnType("bigint")
                        .HasColumnName("nbr_pages");

                    b.Property<double?>("Prix")
                        .HasColumnType("float")
                        .HasColumnName("prix");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("titre");

                    b.Property<long?>("maison_edition_fk")
                        .HasColumnType("bigint");

                    b.Property<long?>("provenance_fk")
                        .HasColumnType("bigint");

                    b.HasKey("Numéro");

                    b.HasIndex("maison_edition_fk");

                    b.HasIndex("provenance_fk");

                    b.ToTable("livre", "dbo");
                });

            modelBuilder.Entity("BibliothèqueUniversitaire.ApplicationWpfCore.Models.PersoneEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("adress");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nom");

                    b.Property<string>("Prénom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prenom");

                    b.HasKey("Id");

                    b.ToTable("personne", "dbo");
                });

            modelBuilder.Entity("BibliothèqueUniversitaire.ApplicationWpfCore.Models.ProvenanceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_provenance")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("adress");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nom");

                    b.HasKey("Id");

                    b.ToTable("provenance", "dbo");
                });

            modelBuilder.Entity("BibliothèqueUniversitaire.ApplicationWpfCore.Models.AdherentEntity", b =>
                {
                    b.HasBaseType("BibliothèqueUniversitaire.ApplicationWpfCore.Models.PersoneEntity");

                    b.ToTable("adherent", "dbo");
                });

            modelBuilder.Entity("BibliothèqueUniversitaire.ApplicationWpfCore.Models.AuteurEntity", b =>
                {
                    b.HasBaseType("BibliothèqueUniversitaire.ApplicationWpfCore.Models.PersoneEntity");

                    b.ToTable("auteur", "dbo");
                });

            modelBuilder.Entity("BibliothèqueUniversitaire.ApplicationWpfCore.Models.MaisonEditionEntity", b =>
                {
                    b.HasBaseType("BibliothèqueUniversitaire.ApplicationWpfCore.Models.ProvenanceEntity");

                    b.Property<string>("NomRespensable")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nom_respensable");

                    b.ToTable("maison_edition", "dbo");
                });

            modelBuilder.Entity("AuteurEntityLivreEntity", b =>
                {
                    b.HasOne("BibliothèqueUniversitaire.ApplicationWpfCore.Models.AuteurEntity", null)
                        .WithMany()
                        .HasForeignKey("AuteursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BibliothèqueUniversitaire.ApplicationWpfCore.Models.LivreEntity", null)
                        .WithMany()
                        .HasForeignKey("LivresNuméro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BibliothèqueUniversitaire.ApplicationWpfCore.Models.EmpruntEntity", b =>
                {
                    b.HasOne("BibliothèqueUniversitaire.ApplicationWpfCore.Models.AdherentEntity", "Adherent")
                        .WithMany("Emprunts")
                        .HasForeignKey("AdherentId");

                    b.HasOne("BibliothèqueUniversitaire.ApplicationWpfCore.Models.LivreEntity", "LivreEmprunté")
                        .WithMany()
                        .HasForeignKey("LivreEmpruntéNuméro");

                    b.Navigation("Adherent");

                    b.Navigation("LivreEmprunté");
                });

            modelBuilder.Entity("BibliothèqueUniversitaire.ApplicationWpfCore.Models.LivreEntity", b =>
                {
                    b.HasOne("BibliothèqueUniversitaire.ApplicationWpfCore.Models.ProvenanceEntity", "MaisonEdition")
                        .WithMany()
                        .HasForeignKey("maison_edition_fk");

                    b.HasOne("BibliothèqueUniversitaire.ApplicationWpfCore.Models.ProvenanceEntity", "Provenance")
                        .WithMany()
                        .HasForeignKey("provenance_fk");

                    b.Navigation("MaisonEdition");

                    b.Navigation("Provenance");
                });

            modelBuilder.Entity("BibliothèqueUniversitaire.ApplicationWpfCore.Models.AdherentEntity", b =>
                {
                    b.HasOne("BibliothèqueUniversitaire.ApplicationWpfCore.Models.PersoneEntity", null)
                        .WithOne()
                        .HasForeignKey("BibliothèqueUniversitaire.ApplicationWpfCore.Models.AdherentEntity", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BibliothèqueUniversitaire.ApplicationWpfCore.Models.AuteurEntity", b =>
                {
                    b.HasOne("BibliothèqueUniversitaire.ApplicationWpfCore.Models.PersoneEntity", null)
                        .WithOne()
                        .HasForeignKey("BibliothèqueUniversitaire.ApplicationWpfCore.Models.AuteurEntity", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BibliothèqueUniversitaire.ApplicationWpfCore.Models.MaisonEditionEntity", b =>
                {
                    b.HasOne("BibliothèqueUniversitaire.ApplicationWpfCore.Models.ProvenanceEntity", null)
                        .WithOne()
                        .HasForeignKey("BibliothèqueUniversitaire.ApplicationWpfCore.Models.MaisonEditionEntity", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BibliothèqueUniversitaire.ApplicationWpfCore.Models.AdherentEntity", b =>
                {
                    b.Navigation("Emprunts");
                });
#pragma warning restore 612, 618
        }
    }
}
